# PRODUCTION docker-compose.yml
# This file defines the production environment.
# Use `docker-compose -f docker-compose.yml up --build -d` to run.

services:
  easyopen_postgis:
    container_name: easyopen_postgis # Prod specific name
    image: postgis/postgis:17-3.5
    restart: always
    ports:
      - "8735:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data # Prod specific volume
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$DATABASE_NAME"]
      interval: 10s
      timeout: 8s
      retries: 40
    networks:
      - easyopen_network

  easyopen_backend:
    container_name: easyopen_backend # Prod specific name
    build:
      context: ./backend
      dockerfile: Dockerfile # Assumes this Dockerfile is suitable for prod (no dev tools)
    command: uvicorn app.main:app --host 0.0.0.0 --port 5400 # NO --reload for production
    volumes:
      # Code is built into the image for production. Mount only persistent data.
      - ./data/tileset:/data/tileset # Path for tileset data
      - ./data/tempfiles:/data/tempfiles # Path for temporary OBJ files
    ports:
      - "5400:5400"
    environment:
      DATABASE_URL: postgresql+asyncpg://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD}@easyopen_postgis:5432/${DATABASE_NAME:-easyopendata_database}
      STRIPE_SECRET_KEY: ${VITE_STRIPE_SECRET_KEY:?err_VITE_STRIPE_SECRET_KEY_not_set} # Use actual prod key here via .env
      FRONTEND_URL: ${FRONTEND_URL}
      PYTHONUNBUFFERED: "1"
      LOG_LEVEL: "INFO"
      ENVIRONMENT: "production"
    depends_on:
      easyopen_postgis:
        condition: service_healthy
    networks:
      - easyopen_network

  easyopen_frontend:
    container_name: easyopen_frontend # Prod specific name
    build:
      context: ./frontend
      dockerfile: Dockerfile.production # Use the new production Dockerfile
      args: # Pass build arguments needed by Dockerfile.production
        VITE_BASE_URL: ${VITE_BASE_URL}
        VITE_TILESET_URL: ${VITE_TILESET_URL}
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY} # Use actual prod key here via .env
    ports:
      - "5173:80" # Nginx in Dockerfile.production will serve on port 80
    # No volumes for code/node_modules needed as it's a static build served by Nginx
    # Environment variables here are for Nginx if needed, Vite vars are build-time.
    networks:
      - easyopen_network

  easyopen_tileset: # Tileset server remains largely the same
    container_name: easyopen_tileset # Prod specific name
    image: nginx:alpine
    restart: always
    ports:
      - "5576:80"
    volumes:
      - ./data/tileset:/usr/share/nginx/html:ro # Serve from the main data directory
      - ./backend/tileset.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - easyopen_network

  easyopen_backup_service: # Backup service remains largely the same
    container_name: easyopen_backup_service # Prod specific name
    build: ./backend/db_backup
    depends_on:
      - easyopen_postgis
    volumes:
      - ./data/postgres_backups:/backups
    environment:
      PGHOST: easyopen_postgis # Explicitly set PGHOST for pg_dump
      PGUSER: ${DATABASE_USER:-postgres}
      PGDATABASE: ${DATABASE_NAME:-easyopendata_database}
      PGPASSWORD: ${DATABASE_PASSWORD} # PGPASSWORD is used by pg_dump
    networks:
      - easyopen_network

  easyopen_pgadmin:
    container_name: easyopen_pgadmin # Prod specific name
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes: # Add a volume for pgAdmin data persistence
      - ./data/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - easyopen_postgis
    networks:
      - easyopen_network

  easyopen_cloudflared: # Assumed needed for production as well
    container_name: easyopen_cloudflared # Prod specific name
    image: cloudflare/cloudflared:latest
    restart: always
    command: 'tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN:?err_CLOUDFLARED_TOKEN_not_set}'
    depends_on:
      - easyopen_backend
      - easyopen_frontend
      - easyopen_tileset # Add this if you are tunneling the tileset service as well
    networks:
      - easyopen_network # CORRECTED: Should be on the same bridge network

volumes:
  postgres_data: # Renamed for production
    name: easyopen_pgdata_main
  pgadmin_data: # Added for pgAdmin persistence
    name: easyopen_pgadmin_data_main

networks:
  easyopen_network: # Renamed for production
    name: easyopenuction_net
    driver: bridge