services:
  postgis:
    image: postgis/postgis:17-3.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: barcelona
    volumes:
      - postgis_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./backend/tileset:/app/tileset
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:barcelona@postgis:5432/easyopendata_database
    depends_on:
      - postgis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    command: npm run dev
    environment:
      VITE_BACKEND_URL: http://localhost:8000

volumes:
  postgis_data:
