# PRODUCTION docker-compose.yml
# This file defines the core production services, fronted by a reverse proxy.
# Use `docker-compose up --build -d` to run.

services:
  nginx_proxy:
    container_name: easyopen_proxy
    image: nginx:alpine
    restart: always
    ports:
      - "5173:80" # Expose only the reverse proxy to the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - easyopen_backend
      - easyopen_frontend
    networks:
      - easyopen_network

  easyopen_postgis:
    container_name: easyopen_postgis
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 8s
      retries: 40
    networks:
      - easyopen_network

  easyopen_backend:
    container_name: easyopen_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 5400
    restart: always
    volumes:
      - ./data/tempfiles:/data/tempfiles
    environment:
      DATABASE_URL: postgresql+asyncpg://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD}@easyopen_postgis:5432/${DATABASE_NAME:-easyopendata_database}
      STRIPE_SECRET_KEY: ${VITE_STRIPE_SECRET_KEY:?err_VITE_STRIPE_SECRET_KEY_not_set}
      FRONTEND_URL: ${FRONTEND_URL}
      PYTHONUNBUFFERED: "1"
      LOG_LEVEL: "INFO"
      ENVIRONMENT: "production"
    depends_on:
      easyopen_postgis:
        condition: service_healthy
    networks:
      - easyopen_network

  easyopen_frontend:
    container_name: easyopen_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
        VITE_TILESET_URL: ${VITE_TILESET_URL}
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
    restart: always
    volumes:
      # Mount the tileset data into a sub-directory of the Nginx root
      - ./data/tileset:/usr/share/nginx/html/tileset:ro
    networks:
      - easyopen_network

volumes:
  postgres_data:
    name: easyopen_pgdata_main
  pgadmin_data:
    name: easyopen_pgadmin_data_main

networks:
  easyopen_network:
    name: easyopen_production_net
    driver: bridge
