# DEVELOPMENT docker-compose.dev.yml
# This file is for local development and includes tools like pgAdmin.
# It overrides the production compose file to enable hot-reloading and direct port access.
# Use `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build` to run.

services:
  easyopen_backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 5400 --reload
    volumes:
      - ./backend:/app
    ports:
      - "5400:5400"
    environment:
      DATABASE_URL: postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@easyopen_postgis:5432/${DATABASE_NAME}
      # For dev, the frontend is on a different port, so we need the full URL for CORS
      FRONTEND_URL: http://localhost:5173
      LOG_LEVEL: "DEBUG"
      ENVIRONMENT: "development"

  easyopen_frontend:
    # In development, we use the Vite dev server directly from the node image.
    build:
      context: ./frontend
      dockerfile: Dockerfile # This uses the development Dockerfile
    volumes:
      - ./frontend:/app
      - ./data/tileset:/app/public/tileset:ro # Mount tileset into public dir for Vite
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      # Vite needs to know where to send API requests
      VITE_BASE_URL: http://localhost:5400
      # Vite dev server will now serve tiles from its public folder
      VITE_TILESET_URL: http://localhost:5173/tileset/tileset.json
      CHOKIDAR_USEPOLLING: "true"

  easyopen_pgadmin:
    container_name: easyopen_pgadmin_dev
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin_data:/var/lib/pgadmin
    networks:
      - easyopen_network
